# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Delete_readlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_FORM(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(337, 241)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(500, 70))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.delbookbtn = QtWidgets.QLineEdit(Form)
        self.delbookbtn.setObjectName("delbookbtn")
        self.gridLayout.addWidget(self.delbookbtn, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.delautbtn = QtWidgets.QLineEdit(Form)
        self.delautbtn.setObjectName("delautbtn")
        self.gridLayout.addWidget(self.delautbtn, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.delgenrebtn = QtWidgets.QLineEdit(Form)
        self.delgenrebtn.setObjectName("delgenrebtn")
        self.gridLayout.addWidget(self.delgenrebtn, 3, 1, 1, 1)
        self.delselfilebtn = QtWidgets.QPushButton(Form)
        self.delselfilebtn.setObjectName("delselfilebtn")
        self.gridLayout.addWidget(self.delselfilebtn, 4, 0, 1, 1)
        self.filenameedt = QtWidgets.QLineEdit(Form)
        self.filenameedt.setObjectName("filenameedt")
        self.gridLayout.addWidget(self.filenameedt, 4, 1, 1, 1)
        self.deletebtn = QtWidgets.QPushButton(Form)
        self.deletebtn.setObjectName("deletebtn")
        self.gridLayout.addWidget(self.deletebtn, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Удалить из прочитанного"))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Информация о книге</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Название книги:</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Автор книги:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Жанр:</span></p></body></html>"))
        self.delselfilebtn.setText(_translate("Form", "выбрать файл"))
        self.deletebtn.setText(_translate("Form", "удалить"))
        self.label_6.setText(_translate("Form", ""))
