# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inprocess.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FOrm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.append4 = QtWidgets.QPushButton(Form)
        self.append4.setObjectName("append4")
        self.gridLayout.addWidget(self.append4, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.delete4 = QtWidgets.QPushButton(Form)
        self.delete4.setObjectName("delete4")
        self.gridLayout.addWidget(self.delete4, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "В процессе"))
        self.append4.setText(_translate("Form", "В избранное"))
        self.pushButton_3.setText(_translate("Form", "Продолжить чтение"))
        self.delete4.setText(_translate("Form", "Удалить"))
