# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_for_proj.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommonReader(object):
    def setupUi(self, CommonReader):
        CommonReader.setObjectName("CommonReader")
        CommonReader.resize(420, 341)
        CommonReader.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(CommonReader)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.aboutProgramm = QtWidgets.QPushButton(self.centralwidget)
        self.aboutProgramm.setObjectName("aboutProgramm")
        self.gridLayout.addWidget(self.aboutProgramm, 0, 0, 1, 1)
        self.startbtn = QtWidgets.QPushButton(self.centralwidget)
        self.startbtn.setObjectName("startbtn")
        self.gridLayout.addWidget(self.startbtn, 0, 1, 1, 1)
        self.startpicture = QtWidgets.QLabel(self.centralwidget)
        self.startpicture.setMaximumSize(QtCore.QSize(200, 200))
        self.startpicture.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startpicture.setObjectName("label")
        self.gridLayout.addWidget(self.startpicture, 1, 0, 1, 1)
        CommonReader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CommonReader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        CommonReader.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CommonReader)
        self.statusbar.setObjectName("statusbar")
        CommonReader.setStatusBar(self.statusbar)

        self.retranslateUi(CommonReader)
        QtCore.QMetaObject.connectSlotsByName(CommonReader)

    def retranslateUi(self, CommonReader):
        _translate = QtCore.QCoreApplication.translate
        CommonReader.setWindowTitle(_translate("CommonReader", "MainWindow"))
        self.aboutProgramm.setText(_translate("CommonReader", "О программе"))
        self.startbtn.setText(_translate("CommonReader", "начать"))
        self.startpicture.setText(_translate("CommonReader", "startpicture"))
