# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Library.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(456, 405)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 3)
        self.append = QtWidgets.QPushButton(Form)
        self.append.setObjectName("append")
        self.gridLayout.addWidget(self.append, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.beginreadding = QtWidgets.QPushButton(Form)
        self.beginreadding.setObjectName("beginreadding")
        self.gridLayout.addWidget(self.beginreadding, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Library"))
        self.append.setText(_translate("Form", "Добавить"))
        self.pushButton_2.setText(_translate("Form", "удалить"))
        self.beginreadding.setText(_translate("Form", "Начать читать"))
